<a href="https://colab.research.google.com/github/Colette-c/MAT-422/blob/main/HW_1_3_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# QR Decomposition

Using Gram-Schmidt Process to create the set of orthonormal vectors $q_1,...,q_m$ that form a orthonormal basis for the set of vectors $a_1,...,a_m$.

We let $A=(a_1,...,a_m)$ and $Q=(q_1,...,q_m)$. The QR decomposition is $A=QR$, where $R$ is a $m \times m$ matrix that contains the coefficients of the linear combination of $q_i$'s that produces $a_i$. $R$ is an uppertriangular matrix.

In the example below, we can see that the product of a matrix $Q$ and a matrix $R$ is the matrix $A$ satisfying $A=QR$

In [6]:
import numpy as np

A = np.random.randint(10, size = (3,3))
Q, R = np.linalg.qr(A)
print('A = \n', A)
print('Q = \n', Q)
print('R = \n', R)
print('QR = \n', ((np.matmul(Q,R))))

A = 
 [[5 8 3]
 [4 3 8]
 [0 5 7]]
Q = 
 [[-0.78086881  0.2929674  -0.55173726]
 [-0.62469505 -0.36620925  0.68967157]
 [-0.          0.88321055  0.46897667]]
R = 
 [[-6.40312424 -8.12103562 -7.34016681]
 [ 0.          5.66116423  4.13170206]
 [ 0.          0.          7.1449975 ]]
QR = 
 [[5. 8. 3.]
 [4. 3. 8.]
 [0. 5. 7.]]


# Least Squares Problems

Let $A$ be an $n \times m$ vector and $b \in \mathbb{R}^n$ be a vector. A least-squares problem will try to solve the system $Ax=b$ such that we minimize $||Ax-b||$, where $n>m$. If $A$ is a square matrix, we can just find the matrix inverse. To solve for x, we use QR decomposition, because we know that the solution x will satisfy the equation $Rx=Q^T b$.

In [17]:
A = np.random.randint(10, size = (4,3))
b = np.random.randint(10, size=(4,1))
Q, R = np.linalg.qr(A)
x = np.matmul(np.matmul(np.linalg.inv(R),np.transpose(Q)),b)
print('b = \n', b)
print('x approximation = \n',x)
print('Ax = \n', np.around(np.matmul(A,x)))

b = 
 [[0]
 [6]
 [1]
 [7]]
x approximation = 
 [[ 0.25201362]
 [-0.18964882]
 [ 0.36889584]]
Ax = 
 [[4.]
 [4.]
 [1.]
 [4.]]


# Linear Regression

Linear Regression is the use of least-squares method to approximate a function to fit a set of data $\{(x_i,y_i)\}_{i=1}^n$ where the approx. function can be defined as $\hat{y}_i = \beta_0 ∑_{j=1}^d\beta_jx_{ij}$ where least squares is used to minimize the value of the set of coefficients $\beta_j$.