<a href="https://colab.research.google.com/github/Colette-c/MAT-422/blob/main/HW_1_2_Elements_of_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Spaces

Definition: A **linear subspace** of $V$ is a subset $U ⊆ V$ that is closed under vector addition and scalar multiplication.

Definition: Let $w_1,...,w_m \in V$. The **span** of $\{w_1,...,w_m\}$, denoted $span(w_1,...,w_m)$, is the set of all linear combinations of the $w_j$'s.

The following example shows just one linear combination, or one element of the spanning set for $V$, when $V=(1,0,2)$.


In [1]:
V = [1,0,2]
a1=6; a2=4; a3=2
A = [a1,a2,a3]
span = A[0]*V[0] + A[1]*V[1] + A[2]*V[2]
print(span)

10


Definition: A list of vectors $u_1,..., u_m$ is **linearly independent** if none of them can be written as a linear combination of the others, that is,
$∀i, u∉span(\{u_j:j\neq i\})$.

Lemma: The vectors $u_1,...,u_m$ are linearly independent if and only if $∑_{j=1}^m α_ju_j=0 \Longrightarrow α_j = 0. \forall j.$

Definition: Let $A\in \mathbb{R}^{n×m}$ be an $n \times m$ matrix with columns $a_1,...,a_m \in \mathbb{R}^n$. The **column space** of A is the span of the columns of A, or $col(A) = span(a_1,...,a_m)\in \mathbb{R}^n$.

Definition: Let $U$ be a linear subspace of $V$. A basis of $U$ is a list of vectors $u_1,...,u_m$ in $U$ that: 1. span $U$; and 2. are linearly independent.

All bases of a linear subspace will have the same number of elements. This length of the basis is called the **dimension** of the linear subspace ($dim(U)$). Similarly the dimension, or length of a column space is called the rank.

# Orthogonality

Norm and Inner Product: $⟨u, v⟩=u ⋅ v=∑_i^n{u_iv_i}$ and $||u||=\sqrt{∑_1^n{u_i^2}}$

Definition: A list of vectors are **orthonormal** when the inner product $\langle u_i,u_j\rangle = 0$ and the norm of each is $||u_i||=1$

The following example will find the norm and inner products of a list of vectors. We can see that this list of vectors are not orthonormal, but the first two elements of the list are orthonormal because their inner product is 0 and their respective norms are 1.

In [2]:
import numpy as np

def norm(ui):
  n = ui[0]**2 + ui[1]**2 + ui[2]**2
  return n
def inner(u,v):
  dot = u[0]*v[0] + u[1]*v[1] + u[2]*v[2]
  return dot

In [13]:
u = [[1,0,0],[0,1,0],[0,0,2],[1,1,1]]
for i in u:
  for j in u:
    if i==j:
      uinorm = norm(i)
    else:
      ui_uj = inner(i,j)
      print('inner product of u',u.index(i)+1,'and u',u.index(j)+1,': ',ui_uj)
  print('norm of u',u.index(i)+1,': ',uinorm)

inner product of u 1 and u 2 :  0
inner product of u 1 and u 3 :  0
inner product of u 1 and u 4 :  1
norm of u 1 :  1
inner product of u 2 and u 1 :  0
inner product of u 2 and u 3 :  0
inner product of u 2 and u 4 :  1
norm of u 2 :  1
inner product of u 3 and u 1 :  0
inner product of u 3 and u 2 :  0
inner product of u 3 and u 4 :  2
norm of u 3 :  4
inner product of u 4 and u 1 :  1
inner product of u 4 and u 2 :  1
inner product of u 4 and u 3 :  2
norm of u 4 :  3


Orthogonal Projection: Let $\mathcal{U} \subseteq V$ be a linear subspace with orthonormal basis $q_1,...,q_m$. The orthogonal projection of $v \in V$ on $\mathcal{U}$ is defined as $\mathcal{P}_\mathcal{U}v=∑_{j=1}^m⟨v,q_j⟩q_j$.

Best Approximation Theorem: Let $\mathcal{U} \subseteq V$ be a linear subspace with orthonormal basis $q_1,...,q_m$ and let $v ∈ V$. For any $u \in \mathcal{U}$: $||v-\mathcal{P}_\mathcal{U}v|| ≤ ||v-u||$

# Gram-Schmidt Process

Using the set of vectors from the previous example, $u_1,...,u_4$ we will preform the Gram-Schmidt Process to create a set of orthonormal vectors $e_1,...,e_4$.

$v_1 = u_1 = [1,0,0] \\
e_1 = \frac{v_1}{||v_1||}=[1,0,0] \\
v_2 = u_2 - \mathcal{P}_{v_1}u_2 = [0,1,0] - [0,0,0] \\
e_2 = \frac{v_2}{||v_2||}=[0,1,0] \\
v_3 = u_3 - \mathcal{P}_{v_1}u_3 - \mathcal{P}_{v_2}u_3 = [0,0,2] - [0,0,0] - [0,0,0] \\ e_3 = \frac{v_3}{||v_3||} \\
v_4 = u_4 - \mathcal{P}_{v_1}u_4 - \mathcal{P}_{v_2}u_4 - \mathcal{P}_{v_3}u_4 = [2,2,2] - [2,0,0] - [0,2,0] - [0,0,2] = [0,0,0] \\ e_4 = [0,0,0]$

So our list of vector goes from $([1,0,0],[0,1,0],[0,0,2],[2,2,2])$ to $([1,0,0],[0,1,0],[0,0,1],[0,0,0])$

# Eigenvalues and Eigenvectors

Definition: Let $A \in \mathbb{R}^{d\times d}$ be a square matrix. Then $λ \in \mathbb{R}$ is an **eigenvalue** of $A$ if there exists a nonzero vector $x\neq 0$ such that $Ax=λx$. The vector $x$ is referred to as an eigenvector.

In [4]:
A = np.array([[2,6,2],[3,4,1],[5,2,2]])

l,x = np.linalg.eig(A)
print('eigenvalues of A = ',l)
print('eigenvectors of A = ',x)

eigenvalues of A =  [ 8.84911069 -2.05745852  1.20834783]
eigenvectors of A =  [[-0.6191055  -0.66547415 -0.02505382]
 [-0.50674245  0.21140289 -0.31315186]
 [-0.59993372  0.71585821  0.94937254]]


$diag(λ_1,...,λ_d)$ is the notation for the diagonal of a matrix.

Let $A$ be similar to matrix $D = diag(λ_1,...,λ_d)$ with distinct diagonal entries, then there exists a nonsingular matix $P$ such that $A = PDP^{-1}$

Theorem: If $A$ is symmentric, then any two eigenvectors from different eigenspaces are orthogonal.

In [10]:
B = np.array([[1,7,3],[7,4,5],[3,5,2]])

l,x = np.linalg.eig(B)
print('eigenvalues of B = ',l)
print('eigenvectors of B = ',x)
print('inner product of eigenvectors of B = ',round(np.dot(x[0],x[1])))

eigenvalues of B =  [12.76668248 -4.80486473 -0.96181775]
eigenvectors of B =  [[-0.53632236 -0.71906617 -0.44193005]
 [-0.69847327  0.67207302 -0.24587181]
 [-0.47380736 -0.17680978  0.86269629]]
inner product of eigenvectors of B =  0


We know that the matrix $B$ is symmetric because the inner product of its distinct eigenvectors is equal to $0$ meaning that these eigenvectors are orthogonal.